### ISSUE TITLE
Propose structure for the documentation

### ISSUE THREAD

**Issue by uxte** [colab-at/colab#1]
- [x] Make post for discussion - https://github.com/orgs/colab-at/discussions/4#discussion-4946130

**Comment by andreaadao** [comment]
- [x] Make post for discussion - https://github.com/orgs/colab-at/discussions/4#discussion-4946130

**Comment by andreaadao** [comment]
**#update** here: [https://github.com/orgs/colab-at/discussions/4#discussioncomment-5392610](https://github.com/orgs/colab-at/discussions/4#discussioncomment-5392610)
